apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.myconfigmap.metadata.name}}
data:
{{- with .Values.myconfigmap.data }}
  ENVIRONMENT: {{.ENVIRONMENT | quote }}
  HOST: {{ .HOST |quote }}
  PORT: {{.PORT | quote }}
  REDIS_HOST: {{.REDIS_HOST |quote }}
  REDIS_PORT: {{.REDIS_PORT | quote}}
  REDIS_DB: {{.REDIS_DB | quote}}
  {{- end}}