apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appsvc.metadata.name}}
spec:
  type: {{.Values.appsvc.spec.type}}
  selector:
    name: {{.Values.appsvc.selector.name}}
  ports:
    - protcol: {{.Values.appsvc.ports.portcol}}
      port: {{.Values.appsvc.ports.port}}
      targetPort: {{.Values.appsvc.ports.port}}
