apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redissvc.metadata.name}}
spec:
  selector:
    name: {{.Values.redissvc.selector.name}}
  ports:
  {{- with .Values.redissvc.ports}}
    - protocol: {{.protocol}}
      port: {{.port}}
      targetPort: {{.port}}
  {{- end}}